<div class='wrap'>

    <div class='mapicon icon32'><br/></div>

    <h2 style='padding-bottom:10px'>Edit Map</h2>
    
    <?php require('common/messages.phtml') ?>
    
    <form method='post' action='<?php echo admin_url('admin.php?page=' . SpatialMatch_Controller_Admin::MENU_ID) ?>'>
        
        <input type='hidden' name='action' value='update' />
        <input type='hidden' name='id' value='<?php echo $this->view->map->id ?>' />
        
        <?php wp_nonce_field(); ?>

        <?php require('admin-map-form.phtml'); ?>
        
    </form>
    
</div>
