<div class='wrap'>

    <div class='icon32 icon-site'><br/></div>

    <h2>SpatialMatch&reg; License Keys</h2>

    <?php require('common/messages.phtml') ?>

    <p />
    
    <form name='spatialmatch-license-keys-form' class='spatialmatch-license-keys-form' method='post' action='options.php'>
    
        <table class='wp-list-table widefat fixed' cellspacing='0' style='width:600px'>

            <thead>
                <tr>
                    <th class='manage-column'>License Keys</th>
                    <th class='manage-column' style='width:75px'>Actions</th>
                </tr>
            </thead>
                    
            <tbody>
<?php
                if (count($this->view->licenseKeys) > 0)
                {
                    $alternate = true;
        
                    foreach ($this->view->licenseKeys as $licenseKey)
                    {
?>                        
                        <tr <?php if ($alternate) echo ' class="alternate"'; ?>>
                
                            <td>
                                <?php echo $licenseKey ?>
                            </td>
        
                            <td>
<?php
                                $fragment = 'admin.php?page=' . self::MENU_ID . '-licenses&action=delete-license&licenseKey=' . $licenseKey;
?>                                            
                                <a href='<?php echo admin_url($fragment)?>'>Delete</a>
                            </td>
                        </tr>
<?php
                        $alternate = !$alternate;
                    }
                }
                else
                {
?>
                    <tr>
                        <td colspan='2'>
                            You have not specified any license keys. &nbsp;
                            <a href='<?php echo admin_url('admin.php?page=' . self::MENU_ID . '-licenses&action=add-license')?>'><b>Add one now!</b></a>
                        </td>
                    </tr>
<?php
                }
?>
            </tbody>
            
        </table>
    
        <p />
        
        <a href='<?php echo admin_url('admin.php?page=' . self::MENU_ID . '-licenses&action=add-license')?>' style='text-decoration:none'>        
            <input class='button-secondary' type='button' value='Add License Key' style='width:125px' />
        </a>
        
    </form>
    
</div>
