<div class='wrap spatialmatch-help'>

    <div class='icon32 helpicon'><br/></div>

    <h2>SpatialMatch<span class='sm-reg'>&reg;</span> Help</h2>

    <?php require('common/messages.phtml') ?>

    <p />

    <p>
        Please review our help documentation <a href='http://dashboard.homejunction.com/help'>here</a>.  If you still can't find the information that
        you are looking for, feel to <a href='http://dashboard.homejunction.com/help/contact'>contact us</a>.        
    </p>

    <ul>
        <li>(858) 777-9533 Ext. 4</li>
        <li class="sm-icon-2">
            <a href="mailto:help@homejunction.com">help@homejunction.com</a>
        </li>
    </ul>
    
    <p>
        The Home Junction <a href='http://dashboard.homejunction.com'>Customer Dashboard</a> allows you to configure and manage
        your SpatialMatch<span class='sm-reg'>&reg;</span> application.  Some of the things you might want to do include:
    </p>
    
    <ul>
        <li class='sm-icon-5'>
            <a href="http://dashboard.homejunction.com/opportunities">Manage your leads</a>
        </li>

        <li class='sm-icon-3'>
            <a href="http://dashboard.homejunction.com/opportunities">View usage and analytics</a>
        </li>

        <li class='sm-icon-4'>
            <a href="http://dashboard.homejunction.com/opportunities">Change the plugin behavior</a>
        </li>

        <li class='sm-icon-6'>
            <a href="http://dashboard.homejunction.com/help/cases/create">Open a support case</a>
        </li>
    </ul>    
    
    <p>
        You should have received your <a href='http://dashboard.homejunction.com'>Customer Dashboard</a> login credentials when you
        signed up for the SpatialMatch<span class='sm-reg'>&reg;</span> WordPress plugin.  If you need help logging in, please contact our support department
        by phone at <strong>(858) 777-9533 (Ext. 4)</strong> or via email at <a href="mailto:help@homejunction.com">help@homejunction.com</a>.
    </p>
</div>
