<div class='wrap'>
    
    <div class='mapicon icon32'><br/></div>

    <h2 style='padding-bottom:10px'>
        Maps <a href='?page=<?php echo SpatialMatch_Controller_Admin::MENU_ID ?>-add' class='add-new-h2'>Add New Map</a>
    </h2>

    <?php require('common/messages.phtml') ?>

    <p />

    <form name='spatialmatch-maps-form' class='form-fields item-list-form' method='get'>

        <input type='hidden' name='page' value='<?php echo SpatialMatch_Controller_Admin::MENU_ID ?>' />
<?php        
        $this->view->mapList->search_box('Search', 'x'); 

        $this->view->mapList->display();
?>
    </form>

    <h2 style='padding-bottom:10px'>
        <a href='?page=<?php echo SpatialMatch_Controller_Admin::MENU_ID ?>-add' class='button-primary'>Add New Map</a>
    </h2>

</div>
