
<?php
    $instance = $this->view->instance;
    $widget = $this->view->widget;
    
    $uid = uniqid('sm-search-widget-');        

    $categories = isset($instance['categories']) ? $instance['categories'] : null;

    $title = isset($instance['title']) ? trim($instance['title']) : null;

    $target = isset($instance['target']) ? trim($instance['target']) : '';

    $location = isset($instance['location']) ? trim($instance['location']) : '';

    $zoom = isset($instance['zoom']) ? trim($instance['zoom']) : '';

    $options = '';
    
    if ($target == 'popup')
    {
        $width = ($instance['popup_width'] != null) ? ('"' . $instance['popup_width']  . '"') : 'null';
        $height = ($instance['popup_height'] != null) ? ('"' . $instance['popup_height']  . '"') : 'null';
        
        $options = '{width:' . $width . ',height:' . $height . '}';    
    }
    else if ($target == 'page')
    {        
        $options = '{url:' . (($instance['page_url'] != null) ? ('"' . $instance['page_url']  . '"') : 'null') . '}';
    }
    
    if (!empty($instance['categories']))
    {
?>    
        <div class='spatialmatch-widget-lifestyle-search spatialmatch-widget-search' uid='<?php echo $uid ?>'
            license='<?php echo $this->view->licenseKey ?>' location='<?php echo esc_html($location) ?>'
            zoom='<?php echo esc_html($zoom) ?>' target='<?php echo esc_html($target) ?>|<?php echo esc_html($options) ?>'>    
<?php        
            if (!empty($title))
            {
                if (isset($widget['before_title']))
                {
                    echo $widget['before_title'];
                }
        
                echo esc_html($title);
        
                if (isset($widget['after_title']))
                {
                    echo $widget['after_title'];
                }
            }
?>
            <label for='<?php echo $uid ?>-location'>Location</label>
            
            <input type='text' id='<?php echo $uid ?>-location' value='<?php echo esc_html($location) ?>' />
            
            <fieldset>
                
                <legend>Select the categories that are important to you:</legend>

                <div>                
<?php            
                    foreach ($categories as $category)
                    {
?>
                        <input type='checkbox' class='spatialmatch-widget-lifestyle-category'
                            id='<?php echo $uid ?>-<?php echo $category ?>' category='<?php echo $category ?>' /><br />
<?php
                    }
?>
                </div>
                
            </fieldset>

            <input type='button' class='button' action='search' value='Search' />
        
            <input type='button' class='button' action='reset' value='Reset' />
<?php
            if ($target == 'popup')
            {
?>                
                <div id='<?php echo $uid ?>' class='spatialmatch-search-widget-content-wrapper' style='overflow:hidden'
                    title='<?php echo !empty($title) ? esc_html($title) : 'Lifestyle Search' ?>'></div>
<?php
            }
?>            
        </div>
<?php        
    }
?>
