<?php
    require_once(SpatialMatch::$pluginDir . '/classes/util/CSS.php');

    $widget = $this->view->widget;
    $instance = $this->view->instance;
    
    $categories = isset($instance['categories']) ? $instance['categories'] : array();

    if ($widget->updated == true)
    {
        $s = isset($instance['location']) ? trim($instance['location']) : null;

        if (empty($s))
        {
?>            
            <div class='error'><p style='margin:.5em 0'>Please specify a default location.</p></div>
<?php        
        }
        
        if (isset($instance['target']) && ($instance['target'] == 'page'))
        {
            $s = isset($instance['page_url']) ? trim($instance['page_url']) : null;

            if (empty($s))
            {
?>            
                <div class='error'><p style='margin:.5em 0'>Please specify a lifestyle page URL.</p></div>
<?php        
            }        
        }
    }
?>

<div class='spatialmatch-search-form'>
    
<!-- License Key -->

<?php    
    $currentKey = isset($instance['license_key']) ? trim($instance['license_key']) : '';

    $availableKeys = array();
        
    $match = false;
        
    foreach ($this->view->licenseKeys as $licenseKey)
    {
        if ($licenseKey == $currentKey)
        {
            $match = true;
        }
        
        array_push($availableKeys, $licenseKey);
    }
        
    if ($match == false)
    {
        if (!empty($currentKey))
        {
            array_unshift($availableKeys, $currentKey);
        }
        else
        {
            if (count($availableKeys) > 0)
            {
                $currentKey = $availableKeys[0];
            }
        }
    }

    if (count($availableKeys) > 1)
    {
?>
        <p>
            License Key:
        
            <select name='<?php echo $widget->get_field_name('license_key') ?>'
                id='<?php echo $widget->get_field_id('license_key') ?>' style='width:100%;margin-top:5px'>
<?php
                foreach ($availableKeys as $licenseKey)
                {
                    $match = ($licenseKey == $currentKey) ? true : false;
?>
                    <option value='<?php echo $licenseKey ?>' <?php selected($match) ?>><?php echo $licenseKey ?></option>
<?php
                }
?>
            </select>

        </p>
<?php
    }
    else
    {
?>
        <input type='hidden' name='<?php echo $widget->get_field_name('license_key') ?>' value='<?php echo $currentKey ?>' />
<?php
    }
?>

<!-- Title -->

    <p>
        <label for='<?php echo $widget->get_field_id('title') ?>'>Title:</label>
        
        <input type='text' class='widefat'
            id='<?php echo $widget->get_field_id('title') ?>' name='<?php echo $widget->get_field_name('title') ?>'
            value='<?php echo esc_html($instance['title']) ?>' placeholder='Optional' />
    
    </p>

<!-- Categories -->

    <fieldset>
        
        <legend>Select the lifestyle categories you want to show to the user:</legend>
    
        <div>

            <ul>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('public_schools', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-public_schools'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='public_schools' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-public_schools'>Public Schools</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('private_schools', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-private_schools'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='private_schools' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-private_schools'>Private Schools</label><br />
                </li>
                
                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('grocery_stores', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-grocery_stores'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='grocery_stores' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-grocery_stores'>Grocery Stores</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('golf_courses', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-golf_courses'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='golf_courses' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-golf_courses'>Golf Courses</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('coffee_shops', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-coffee_shops'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='coffee_shops' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-coffee_shops'>Coffee Shops</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('movie_theaters', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-movie_theaters'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='movie_theaters' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-movie_theaters'>Movie Theaters</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('hospitals', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-hospitals'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='hospitals' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-hospitals'>Hospitals</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('hotels', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-hotels'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='hotels' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-hotels'>Hotels</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('casual_dining', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-casual_dining'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='casual_dining' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-casual_dining'>Casual Dining</label><br />
                </li>

                <li>
                    <input class='checkbox' type='checkbox' <?php echo SpatialMatch_Util_CSS::checked(in_array('book_stores', $categories)) ?>
                        id='<?php echo $widget->get_field_id('categories') ?>-book_stores'
                            name='<?php echo $widget->get_field_name('categories') ?>[]' value='book_stores' />
                                <label for='<?php echo $widget->get_field_id('categories') ?>-book_stores'>Book Stores</label><br />
                </li>

            </ul>
            
        </div>

    </fieldset>

    <p />
        
<!-- Location -->
        
    <p>
            
        <label for='<?php echo $widget->get_field_id('location') ?>'>Default Location</label> <span class='description'>(required)</span>
    
        <input type='text' class='widefat'
            id='<?php echo $widget->get_field_id('location') ?>' name='<?php echo $widget->get_field_name('location') ?>'
            value='<?php echo esc_html($instance['location']) ?>' placeholder='City, State or Zip' />
    
    </p>
    
<!-- Zoom Level -->
    
    <p>
        
        <label for='<?php echo $widget->get_field_id('zoom') ?>'>Map Zoom Level</label> <span class='description'>(optional)</span>
    
        <input type='text' class='widefat'
            id='<?php echo $widget->get_field_id('zoom') ?>' name='<?php echo $widget->get_field_name('zoom') ?>'
            value='<?php echo esc_html($instance['zoom']) ?>' placeholder='11 thru 17' />
    
    </p>

<!-- Target  -->

    <p>
        Where do you want to display the selected lifestyles when the user runs this search?
        
        <select name='<?php echo $widget->get_field_name('target') ?>'
            id='<?php echo $widget->get_field_id('target') ?>' style='width:100%;margin-top:10px'
            onchange='SpatialMatch.Admin.Widget.targetChangeHandler(this)'>
            
            <option value='popup' <?php selected($instance['target'] == 'popup') ?>>Popup Window</option>
            <option value='page' <?php selected($instance['target'] == 'page') ?>>Page</option>
            
        </select>                
    </p>

<!-- Popup Settings -->

    <div id='<?php echo $widget->get_field_id('target') ?>-popup'
        style='display:<?php echo ($instance['target'] == 'popup') ? 'block' : 'none' ?>'>
    
        <table style='width:100%'>
        
            <tr>
                <td>
                    <label for='<?php echo $widget->get_field_id('popup_width') ?>'>Popup&nbsp;Width:</label>
                </td>
                
                <td>        
                    <input type='text' class='widefat' style='width:45px'
                        id='<?php echo $widget->get_field_id('popup_width') ?>' name='<?php echo $widget->get_field_name('popup_width') ?>'
                        value='<?php echo esc_html($instance['popup_width']) ?>' />
                </td>
                
                <td>(pixels&nbsp;or&nbsp;%)</td>
            </tr>
                    
            <tr>
                <td>
                    <label for='<?php echo $widget->get_field_id('popup_height') ?>'>Popup&nbsp;Height:</label>
                </td>
        
                <td>
                    <input type='text' class='widefat' style='width:45px'
                        id='<?php echo $widget->get_field_id('popup_height') ?>' name='<?php echo $widget->get_field_name('popup_height') ?>'
                        value='<?php echo esc_html($instance['popup_height']) ?>' />
                </td>
                
                <td>(pixels)</td>
            </tr>
            
            <tr>
                <td colspan='3'><p class='description' style='margin:.5em 0px 0px 0px'>If you leave the sizes blank, the popup will fill the entire browser window.</p></td>
            </tr>
            
        </table>
        
    </div>

<!-- Page Settings -->

    <div id='<?php echo $widget->get_field_id('target') ?>-page'
        style='display:<?php echo ($instance['target'] == 'page') ? 'block' : 'none' ?>'>

        <p>        
            <label for='<?php echo $widget->get_field_id('page_url') ?>' style='display:block;margin-bottom:5px'>
                Specify the URL of the page that will display the selected lifestyles:
            </label>
        
            <input type='text' class='widefat'
                id='<?php echo $widget->get_field_id('page_url') ?>' name='<?php echo $widget->get_field_name('page_url') ?>'
                    value='<?php echo esc_html($instance['page_url']) ?>' />
    
            <span class='description' style='display:block;margin-top:5px'>
                You can use the <code>[spatialmatch_map]</code> shortcode on the specified page to automatically display the selected lifestyles in a SpatialMatch&reg; map.
            </span>
        </p>

    </div>

</div>
