
<?php
    require_once(SpatialMatch::$pluginDir . '/classes/util/String.php');

    $instance = $this->view->instance;
    $widget = $this->view->widget;
    
    $uid = uniqid('sm-search-widget-');        

    $listingType = isset($instance['listingType']) ? $instance['listingType'] : null;

    $fields = isset($instance['fields']) ? $instance['fields'] : null;

    $title = isset($instance['title']) ? trim($instance['title']) : null;

    $target = isset($instance['target']) ? trim($instance['target']) : '';

    $location = isset($instance['location']) ? trim($instance['location']) : '';

    $zoom = isset($instance['zoom']) ? trim($instance['zoom']) : '';
    
    $orientation = isset($instance['orientation']) ? trim($instance['orientation']) : '';

    if ($target == SpatialMatch_Widget_PropertySearch::TARGET_POPUP)
    {
        $popupWidth = ($instance['popup_width'] != null) ? ('"' . $instance['popup_width']  . '"') : 'null';
        $popupHeight = ($instance['popup_height'] != null) ? ('"' . $instance['popup_height']  . '"') : 'null';
        
        $options = '{width:' . $popupWidth . ',height:' . $popupHeight . '}';    
    }
    else if ($target == SpatialMatch_Widget_PropertySearch::TARGET_PAGE)
    {        
        $options = '{url:' . (($instance['page_url'] != null) ? ('"' . $instance['page_url']  . '"') : 'null') . '}';
    }

    if (!empty($listingType) && !empty($instance['fields']))
    {
?>
        <div class='spatialmatch-widget-property-search spatialmatch-widget-search' uid='<?php echo $uid ?>'
            license='<?php echo $this->view->licenseKey ?>' listingType='<?php echo $listingType ?>'
                location='<?php echo esc_html($location) ?>' zoom='<?php echo esc_html($zoom) ?>'
                    target='<?php echo esc_html($target) ?>|<?php echo esc_html($options) ?>'>    
<?php        
            if (!empty($title))
            {
                if (isset($widget['before_title']))
                {
                    echo $widget['before_title'];
                }
        
                echo esc_html($title);
        
                if (isset($widget['after_title']))
                {
                    echo $widget['after_title'];
                }
            }

            if ($orientation == SpatialMatch_Widget_PropertySearch::ORIENTATION_HORIZONTAL)
            {
                $columnCount = isset($instance['column_count']) ? intval($instance['column_count']) : 0;
                
                $columnCount = (is_nan($columnCount) || ($columnCount < 1)) ? 3 : $columnCount;
            
                $columnData = array();
            
                for ($ii = 0; $ii < $columnCount; $ii++)
                {
                    $columnData[$ii] = array();
                }

                $visibleFields = array();
                
                for ($ii = 0; $ii < count(SpatialMatch_Widget_PropertySearch::$FIELDS); $ii++)
                {
                    $field = SpatialMatch_Widget_PropertySearch::$FIELDS[$ii];
                    
                    $isVisible = (in_array($listingType, $field['types']) || in_array('*', $field['types'])) ? true : false;
    
                    if (($isVisible == true) && in_array($field['key'], $fields))
                    {
                        array_push($visibleFields, $field);
                    }
                }

                for ($ii = 0; $ii < count($visibleFields); $ii++)
                {
                    $field = $visibleFields[$ii];

                    $columnIndex = $ii % $columnCount;
                    
                    array_push($columnData[$columnIndex], $field);
                }
    
                $columnStyle = '';
    
                $width = !empty($instance['column_width']) ? trim($instance['column_width']) : '';
    
                $width = (SpatialMatch_Util_String::isNumber($width)) ? ($width . 'px') : $width;

                if (!empty($width))
                {
                    $columnStyle = 'style="width:' . $width . '"';
                }

                for ($ii = 0; $ii < $columnCount; $ii++)
                {
                    $thisColumn = $columnData[$ii];                
?>
                    <div class='spatialmatch-widget-search-column spatialmatch-widget-search-column-<?php echo $ii ?>' <?php echo $columnStyle ?>>
<?php
                        for ($jj = 0; $jj < count($thisColumn); $jj++)
                        {
                            $field = $thisColumn[$jj];
?>                    
                            <div class='spatialmatch-widget-search-field' field='<?php echo $field['key'] ?>'></div>
<?php                    
                        }
?>                
                    </div>
<?php                
                }
?>
                <br style='clear:both' />
<?php
            }
            else
            {
                for ($ii = 0; $ii < count(SpatialMatch_Widget_PropertySearch::$FIELDS); $ii++)
                {
                    $field = SpatialMatch_Widget_PropertySearch::$FIELDS[$ii];
                    
                    $isVisible = (in_array($listingType, $field['types']) || in_array('*', $field['types'])) ? true : false;

                    if (($isVisible == true) && in_array($field['key'], $fields))
                    {
?>
                        <div class='spatialmatch-widget-search-field' field='<?php echo $field['key'] ?>'></div>
<?php
                    }
                }
            }
?>            
            <input type='button' class='button' action='search' value='Search' />
        
            <input type='button' class='button' action='reset' value='Reset' />
<?php
            if ($target == SpatialMatch_Widget_PropertySearch::TARGET_POPUP)
            {
?>                
                <div id='<?php echo $uid ?>' class='spatialmatch-search-widget-content-wrapper' style='overflow:hidden'
                    title='<?php echo !empty($title) ? esc_html($title) : 'Property Search' ?>'></div>
<?php
            }
?>            
        </div>
<?php        
    }
?>
