<?php
    require_once(SpatialMatch::$pluginDir . '/classes/util/String.php');

    $widget = $this->view->widget;
    $instance = $this->view->instance;
    
    if (count($this->view->maps) > 0)
    {
?>
        <p>
            <label for='<?php echo $widget->get_field_id('map') ?>'>Select the map that you want to display:</label>
            
            <select name='<?php echo $widget->get_field_name('map') ?>' id='<?php echo $widget->get_field_id('map') ?>' style='width:100%;margin-top:5px'>
<?php
                $foundIt = false;
                    
                foreach ($this->view->maps as $map)
                {
                    $selected = ($instance['map'] == $map->id) ? true : false;
                        
                    if ($selected == true)
                    {
                        $foundIt = true;
                    }
?>
                    <option value='<?php echo $map->id; ?>' <?php if ($selected) echo 'selected="selected"' ?>
                        ><?php echo esc_html(SpatialMatch_Util_String::truncate($map->title, 50)) ?></option>
<?php
                }
                    
                if (($foundIt == false) && (isset($instance['map'])))
                {
?>
                    <option value='0' selected='selected'></option>
<?php
                }
?>                    
            </select>
<?php                    
            if (($foundIt == false) && (isset($instance['map'])))
            {
?>
                <span class='warning'>Please select a valid map.</span>
<?php                        
            }
?>
        </p>                    

        <p>
            <table cellspacing='5px'>
            
                <tr>
                    <td>
                        <label for='<?php echo $widget->get_field_id('width') ?>'>Map Width:</label>
                    </td>
                    
                    <td>        
                        <input type='text' class='widefat' style='width:50px'
                            id='<?php echo $widget->get_field_id('width') ?>' name='<?php echo $widget->get_field_name('width') ?>'
                            value='<?php echo esc_html($instance['width']) ?>' />
                    </td>
                    
                    <td>(pixels or %)</td>
                </tr>
                        
                <tr>
                    <td>
                        <label for='<?php echo $widget->get_field_id('height') ?>'>Map Height:</label>
                    </td>
            
                    <td>
                        <input type='text' class='widefat' style='width:50px'
                            id='<?php echo $widget->get_field_id('height') ?>' name='<?php echo $widget->get_field_name('height') ?>'
                            value='<?php echo esc_html($instance['height']) ?>' />
                    </td>
                    
                    <td>(pixels)</td>
                </tr>
                
            </table>
        
        </p>
        
        <p>
            <input class='checkbox' type='checkbox' <?php checked($instance['show_title'], true) ?>
                id='<?php echo $widget->get_field_id('show_title') ?>' name='<?php echo $widget->get_field_name('show_title') ?>' value='1' />
            <label for='<?php echo $widget->get_field_id('show_title') ?>'>Show the map title.</label>
        </p>
<?php  
    }
    else
    {
?>
        <p><span class='warning'>You have not created any maps.  <a href='admin.php?page=<?php echo SpatialMatch_Controller_Admin::MENU_ID ?>-add'>Add one now!</a></span></p>
<?php
    }
