<?php
    if (isset($this->view))
    {
        if (isset($this->view->message))
        {
            $message = trim($this->view->message);
            
            if (isset($message) && (strlen($message) > 0))
            {
?>
                <div class='updated fade' style='padding:5px'>
                    <?php echo esc_html($message) ?>
                </div>
<?php
            }
        }
        
        if (isset($this->view->errors))
        {
            $errors = $this->view->errors;
            
            if (is_array($errors) && (count($errors) > 0))
            {
?>                
                <div class='error'>
<?php
                    foreach ($errors as $error)
                    {
?>
                        <p><?php echo esc_html($error) ?></p>
<?php
                    }
?>
                </div>
<?php                
            }
        }        
    }
?>
